export const allFonts = [
  "BrittanySignature",
  "CherriesBlack",
  "PalatinoUnicode",
  "Jester",
  "LucianSchoenschrift",
  "Gabriola",
  "Cambria",
  "CopperplateGothicBold",
  "SteelfishOutline",
  "MonotypeCorsiva",
  "RaiLowercase",
];
export const defaultTextStyles = {
  defaultTextColor: "#ffffff",
  fontSize: 24,
  fontFamily: "BrittanySignature",
};
export const colors = [
  "#e58ee6",
  "#8eb8e6",
  "#ea5d5d",
  "#bdee53",
  "#f8f130",
  "#feb086",
  "#a8ffe9",
  "#41fe34",
  "#ffffff",
];
export const quotesType = {
  Every_Day: ["Birthday", "Anniversary"],
  Emotions_Sentiments: ["Congratulations", "Breakup", "Motivation"],
  Special_Occasions: [
    "Eid",
    "Father's Day",
    "Friendship Day",
    "Independence Day",
    "Women's Day",
    "Holi",
    "Rose Day",
    "Propose Day",
    "Chocolate Day",
    "Teddy Day",
    "Promise Day",
    "Hug Day",
    "Kiss Day",
    "Valentine's Day",
    "Teacher's Day",
    "Grandparent's Day",
    "Daughters Day",
    "New Year",
    "International Coffee Day",
    "World Smile Day",
  ],
  Festivals: [
    "Janmashtami",
    "Ganesh Chaturthi",
    "Karwa Chauth",
    "Dhanteras",
    "Diwali",
    "Bhai Dooj",
    "Christmas",
    "Rakshabandhan",
  ],
};
